#!/usr/bin/env bash
set -euo pipefail

if command -v pacman &>/dev/null; then
	sudo pacman -S --noconfirm --needed go
else
	echo "[go] Arch Linux required"; exit 1
fi

# Create GOPATH directory
mkdir -p "$HOME/go"
