#!/bin/bash

# Check if libfuse2 is installed, and install it if not
if ! dpkg -l | grep -q "libfuse2"; then
    echo "libfuse2 not found, installing..."
    sudo apt update && sudo apt install -y libfuse2 && sudo apt install jq
else
    echo "libfuse2 is already installed."
fi

# Fetch the latest Toolbox App URL
TOOLBOX_URL=$(curl -s https://data.services.jetbrains.com/products?code=TBA\&release.type=eap%2Crc%2Crelease\&fields=distributions%2Clink%2Cname%2Creleases\&_=1734542781370 | jq -r '.[0].releases[0].downloads.linux.link')

if [ -z "$TOOLBOX_URL" ]; then
    echo "Failed to retrieve Toolbox App download URL."
    exit 1
fi

# Download the tarball to /tmp
echo "Downloading Toolbox App from $TOOLBOX_URL..."
wget "$TOOLBOX_URL" -O /tmp/jetbrains-toolbox.tar.gz

# Extract the tarball in /tmp
echo "Extracting Toolbox App..."
tar -xzf /tmp/jetbrains-toolbox.tar.gz -C /tmp
cd /tmp/jetbrains-toolbox-*

# Launch the Toolbox App
echo "Launching Toolbox App..."
./jetbrains-toolbox

# After the first launch, it will be installed at $HOME/.local/share/JetBrains/Toolbox/bin
echo "Toolbox App installed at $HOME/.local/share/JetBrains/Toolbox/bin"

# Clean up the temporary files
echo "Cleaning up temporary files..."
rm -rf /tmp/jetbrains-toolbox-*
rm /tmp/jetbrains-toolbox.tar.gz
