#!/usr/bin/env bash

# Install necessary packages
sudo apt -y update
sudo apt -y install git ripgrep pavucontrol xclip jq tldr python3-pip stow zsh fd-find direnv tree

sudo apt-get remove --purge fzf
sudo apt-get autoremove


# Install fzf from GitHub
echo "Cloning fzf repository..."
git clone --depth 1 git@github.com:junegunn/fzf.git ~/.fzf

# Run the fzf install script
echo "Running fzf install script..."
~/.fzf/install

# Add the fzf setup to .bashrc and .zshrc if not already present
BASHRC_PATH="$HOME/.bashrc"
ZSHRC_PATH="$HOME/.zshrc"

sudo mkdir -p /usr/share/doc/fzf/examples
# Download the completion.bash file
sudo curl -o /usr/share/bash-completion/completions/fzf https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.bash

# Download the key-bindings.bash file
sudo curl -o /usr/share/doc/fzf/examples/key-bindings.bash https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash

# Download the completion.zsh file
curl -o ~/.fzf/completion.zsh https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh

# Download the key-bindings.zsh file
curl -o ~/.fzf/key-bindings.zsh https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh

# Download the key-bindings.fish file
curl -o ~/.fzf/key-bindings.fish https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.fish
