#!/usr/bin/env bash
set -euo pipefail

if command -v pacman &>/dev/null; then
	sudo pacman -S --noconfirm --needed neovim

	# Dependencies for clipboard, treesitter compilation, and mason
	sudo pacman -S --noconfirm --needed xclip wl-clipboard gcc make unzip
else
	echo "[neovim] Arch Linux required"; exit 1
fi
