#!/usr/bin/env bash
set -euo pipefail

if command -v pacman &>/dev/null; then
	sudo pacman -S --noconfirm --needed yazi ffmpeg 7zip jq poppler fd ripgrep fzf zoxide resvg imagemagick
else
	echo "[yazi] Arch Linux required"; exit 1
fi
